ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS student_code TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS avatar_path TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_users_phone ON users(phone) WHERE phone <> '';
